[package]
name = "hello-world-server"
version = "0.1.0"
authors = ["paulbatum"]
edition = "2018"

[dependencies]
hyper = "0.13.7"
tokio = { version =  "0.2.22", features = ["macros"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
base64 = "0.12.3"